; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+6 on Sat Apr 15 2023 16:46:44 GMT-0700 (Pacific Daylight Time)

M561 ; clear any bed transform
G34  ; run auto z-align macro
G29  ; probe the bed and enable compensation
