; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+6 on Sat Apr 15 2023 16:46:44 GMT-0700 (Pacific Daylight Time)
M280 P0 S90 ; retract BLTouch

