; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+6 on Sat Apr 15 2023 16:46:45 GMT-0700 (Pacific Daylight Time)

