; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+6 on Sat Apr 15 2023 16:46:45 GMT-0700 (Pacific Daylight Time)
G91                     ; relative positioning
G1 H2 Z5 F6000          ; lift Z relative to current position
G90				        ; absolute positioning
G1 H0 X290 Y255 F3000   ; move to center of the bed
G30                     ; probe Z
